aws:
  sns:
    enable: true
    accessKey: ${aws.key}
    secretKey: ${aws.secret}
    region: us-east-1
    topicArn: arn:aws:sns:us-east-1:317029018167:sns-spring-boot-lab-topic
server:
  port: 8082
spring:
  application:
    name: "aws-sns-starter-subscriber-example"